//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetBom.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetBom.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Project Sdk=&quot;Microsoft.NET.Sdk.Web&quot;&gt;
        ///
        ///	&lt;PropertyGroup Label=&quot;Globals&quot;&gt;
        ///		&lt;SccProjectName&gt;SAK&lt;/SccProjectName&gt;
        ///		&lt;SccProvider&gt;SAK&lt;/SccProvider&gt;
        ///		&lt;SccAuxPath&gt;SAK&lt;/SccAuxPath&gt;
        ///		&lt;SccLocalPath&gt;SAK&lt;/SccLocalPath&gt;
        ///	&lt;/PropertyGroup&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;TargetFramework&gt;net7.0&lt;/TargetFramework&gt;
        ///		&lt;UserSecretsId&gt;8ebe2f77-e276-40d5-b2ae-eeb77eadbbb7&lt;/UserSecretsId&gt;
        ///		&lt;TypeScriptToolsVersion&gt;3.1&lt;/TypeScriptToolsVersion&gt;
        ///		&lt;DockerDefaultTargetOS&gt;Linux&lt;/DockerDefaultTargetOS&gt;
        ///		&lt;DockerfileContext&gt;..\..&lt;/ [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string _test1 {
            get {
                return ResourceManager.GetString("_test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///	&lt;PropertyGroup Label=&quot;Globals&quot;&gt;
        ///		&lt;SccProjectName&gt;SAK&lt;/SccProjectName&gt;
        ///		&lt;SccProvider&gt;SAK&lt;/SccProvider&gt;
        ///		&lt;SccAuxPath&gt;SAK&lt;/SccAuxPath&gt;
        ///		&lt;SccLocalPath&gt;SAK&lt;/SccLocalPath&gt;
        ///	&lt;/PropertyGroup&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;TargetFramework&gt;net7.0&lt;/TargetFramework&gt;
        ///		&lt;CodeAnalysisRuleSet&gt;..\..\.sonarlint\mydance_mydancecsharp.ruleset&lt;/CodeAnalysisRuleSet&gt;
        ///		&lt;SonarQubeTestProject&gt;False&lt;/SonarQubeTestProject&gt;
        ///	&lt;/PropertyGroup&gt;
        ///
        ///	&lt;ItemGroup&gt;
        ///		&lt;FrameworkReference Include=&quot;Mi [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string _test2 {
            get {
                return ResourceManager.GetString("_test2", resourceCulture);
            }
        }
    }
}
